baseURL = 'https://lea.pet/'
languageCode = 'en-us'
title = 'lea.pet'
enableGitInfo = true
disableKinds = [ "taxonomy", "term" ]

[params.plausible]
  domain = "lea.pet"
  script = "https://stats.fatalerrorcoded.eu/js/stats.js"
  api = "https://stats.fatalerrorcoded.eu/api/stats"

[markup]
  [markup.highlight]
    noClasses = false

[author]
  name = "Lea"
